import { Product } from "./types";

export const newArrivals: Product[] = [
  {
    id: "1",
    title: "Sip of Summer",
    handle: "sip-of-summer",
    description: "A vibrant capture of summer poolside leisure",
    priceRange: { minVariantPrice: { amount: "295", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", altText: "Sip of Summer", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v1", title: "24x36", availableForSale: true, price: { amount: "295", currencyCode: "USD" } } }] },
  },
  {
    id: "2",
    title: "Dreams Are Essentially Silent",
    handle: "dreams-are-essentially-silent",
    description: "A serene coastal dreamscape at golden hour",
    priceRange: { minVariantPrice: { amount: "350", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80", altText: "Dreams Are Essentially Silent", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v2", title: "24x36", availableForSale: true, price: { amount: "350", currencyCode: "USD" } } }] },
  },
  {
    id: "3",
    title: "Salty Flights",
    handle: "salty-flights",
    description: "Aerial photography of ocean waves crashing",
    priceRange: { minVariantPrice: { amount: "275", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=800&q=80", altText: "Salty Flights", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v3", title: "24x36", availableForSale: true, price: { amount: "275", currencyCode: "USD" } } }] },
  },
  {
    id: "4",
    title: "Unmanned Surf Craft",
    handle: "unmanned-surf-craft",
    description: "Lone surfboard resting on pristine sand",
    priceRange: { minVariantPrice: { amount: "320", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1502680390049-dc387e39f8e1?w=800&q=80", altText: "Unmanned Surf Craft", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v4", title: "24x36", availableForSale: true, price: { amount: "320", currencyCode: "USD" } } }] },
  },
  {
    id: "5",
    title: "Turquoise Crowds",
    handle: "turquoise-crowds",
    description: "Aerial view of swimmers in turquoise waters",
    priceRange: { minVariantPrice: { amount: "395", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1530053969600-caed2596d242?w=800&q=80", altText: "Turquoise Crowds", width: 800, height: 1200 } }] },
    variants: { edges: [{ node: { id: "v5", title: "24x36", availableForSale: true, price: { amount: "395", currencyCode: "USD" } } }] },
  },
  {
    id: "6",
    title: "Fastness",
    handle: "fastness",
    description: "Speed and motion captured in coastal light",
    priceRange: { minVariantPrice: { amount: "280", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1484291150605-0860ed671425?w=800&q=80", altText: "Fastness", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v6", title: "24x36", availableForSale: true, price: { amount: "280", currencyCode: "USD" } } }] },
  },
  {
    id: "7",
    title: "Refuel",
    handle: "refuel",
    description: "Vintage americana and coastal vibes",
    priceRange: { minVariantPrice: { amount: "245", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=800&q=80", altText: "Refuel", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v7", title: "24x36", availableForSale: true, price: { amount: "245", currencyCode: "USD" } } }] },
  },
  {
    id: "8",
    title: "Sundown",
    handle: "sundown",
    description: "Golden hour silhouettes against ocean backdrop",
    priceRange: { minVariantPrice: { amount: "310", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1414609245224-afa02bfb3fda?w=800&q=80", altText: "Sundown", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v8", title: "24x36", availableForSale: true, price: { amount: "310", currencyCode: "USD" } } }] },
  },
];

export const bestSellers: Product[] = [
  {
    id: "9",
    title: "Fleetwood",
    handle: "fleetwood",
    description: "Classic automotive beauty meets coastal backdrop",
    priceRange: { minVariantPrice: { amount: "425", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80", altText: "Fleetwood", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v9", title: "24x36", availableForSale: true, price: { amount: "425", currencyCode: "USD" } } }] },
  },
  {
    id: "10",
    title: "Horsepower",
    handle: "horsepower",
    description: "Wild horses running along the shore",
    priceRange: { minVariantPrice: { amount: "380", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1534307671554-9a6d81f4d629?w=800&q=80", altText: "Horsepower", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v10", title: "24x36", availableForSale: true, price: { amount: "380", currencyCode: "USD" } } }] },
  },
  {
    id: "11",
    title: "Happy Days",
    handle: "happy-days",
    description: "Retro summer nostalgia captured perfectly",
    priceRange: { minVariantPrice: { amount: "295", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800&q=80", altText: "Happy Days", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v11", title: "24x36", availableForSale: true, price: { amount: "295", currencyCode: "USD" } } }] },
  },
  {
    id: "12",
    title: "The Daily",
    handle: "the-daily",
    description: "Everyday beauty in extraordinary light",
    priceRange: { minVariantPrice: { amount: "265", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1515266591878-f93e32bc5937?w=800&q=80", altText: "The Daily", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v12", title: "24x36", availableForSale: true, price: { amount: "265", currencyCode: "USD" } } }] },
  },
  {
    id: "13",
    title: "Girls Just Wanna Have Fun",
    handle: "girls-just-wanna-have-fun",
    description: "Playful poolside moments frozen in time",
    priceRange: { minVariantPrice: { amount: "345", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1517191434949-5e90cd67d2b6?w=800&q=80", altText: "Girls Just Wanna Have Fun", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v13", title: "24x36", availableForSale: true, price: { amount: "345", currencyCode: "USD" } } }] },
  },
  {
    id: "14",
    title: "The Dive",
    handle: "the-dive",
    description: "Perfect form captured mid-flight",
    priceRange: { minVariantPrice: { amount: "310", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=800&q=80", altText: "The Dive", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v14", title: "24x36", availableForSale: true, price: { amount: "310", currencyCode: "USD" } } }] },
  },
  {
    id: "15",
    title: "Splash!",
    handle: "splash",
    description: "The joy of water in its purest form",
    priceRange: { minVariantPrice: { amount: "275", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800&q=80", altText: "Splash!", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v15", title: "24x36", availableForSale: true, price: { amount: "275", currencyCode: "USD" } } }] },
  },
  {
    id: "16",
    title: "Fontelina II",
    handle: "fontelina-ii",
    description: "Italian riviera elegance from above",
    priceRange: { minVariantPrice: { amount: "450", currencyCode: "USD" } },
    images: { edges: [{ node: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", altText: "Fontelina II", width: 800, height: 1000 } }] },
    variants: { edges: [{ node: { id: "v16", title: "24x36", availableForSale: true, price: { amount: "450", currencyCode: "USD" } } }] },
  },
];
