# Shopify custom app: from-airtable-sync-catalog
# Deploy config (scopes): shopify app deploy --allow-updates --no-build
client_id = "8b1b256d022e0466fa53236d06d65f3e"
name = "from-airtable-sync-catalog"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[access_scopes]
scopes = "read_orders,write_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,write_files,write_metaobjects,write_products,write_publications"
optional_scopes = ["write_shipping"]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home" ]
